# -*- coding: utf-8 -*-
"""modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hU19Ry8FTvo7MoqGELXdnTvo4KFNAkYa
"""

import sklearn
print(sklearn.__version__)

import pandas as pd
import mlflow
import mlflow.sklearn

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score

# Upload dataset preprocessing
df = pd.read_csv(
    'linebank_reviews_preprocessed.csv'
)

df.head()

# Cek kolom
df.columns

# Memisahkan fitur dan label
X = df['review']
y = df['sentiment']

# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# MLflow Autolog
import mlflow
import mlflow.sklearn

mlflow.sklearn.autolog()

# Buat Model
pipeline = Pipeline([
    (
        'tfidf',
        TfidfVectorizer()
    ),
    (
        'model',
        LogisticRegression(
            max_iter=1000
        )
    )
])

# Training
with mlflow.start_run():

    pipeline.fit(
        X_train,
        y_train
    )

    y_pred = pipeline.predict(
        X_test
    )

    accuracy = accuracy_score(
        y_test,
        y_pred
    )

    print(
        "Accuracy:",
        accuracy
    )
